trigger:
- main

pool:
  name: DevOps-Pool

steps:

- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Yogi-SVC-New'
    backendAzureRmResourceGroupName: 'hubtest'
    backendAzureRmStorageAccountName: 'julystorage11'
    backendAzureRmContainerName: 'julycontainer11'
    backendAzureRmKey: 'y.tfstate'

- task: TerraformTask@5
  displayName: Validate
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: tfsec@1
  displayName: TFsec Scan
  inputs:
    version: 'v1.26.0'

- task: TerraformTask@5
  displayName: Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Yogi-SVC-New'

- task: TerraformTask@5
  displayName: Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '--auto-approve'
    environmentServiceNameAzureRM: 'Yogi-SVC-New'